name: build

on: 
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
    
  pull_request:
    branches: 
    - main
    - release-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NUPKG_OUTDIR: bin/Release/nugets
    steps:
      - uses: actions/checkout@v1
      - name: Parse release version
        run: python ./.github/scripts/get_release_version.py
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build --configuration release
      - name: Generate Packages
        run: dotnet pack --configuration release
      - name: Upload packages
        uses: actions/upload-artifact@master
        with:
          name: packages
          path: ${{ env.NUPKG_OUTDIR }}

  publish:
    name: Publish Packages
    needs: ['build']
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/v') && !(endsWith(github.ref, '-rc') || endsWith(github.ref, '-dev') || endsWith(github.ref, '-prerelease'))
    steps:
    - name: Download release artifacts
      uses: actions/download-artifact@v2
      with:
        name: packages
        path: packages
    - name: List packages (for sanity check)
      run: ls -R
      working-directory: packages
    - name: Publish binaries to github for tags
      if: startswith(github.ref, 'refs/tags/v')
      run: |
        sudo npm install --silent --no-progress -g github-release-cli@1.3.1
        
        # Parse repository to get owner and repo names
        OWNER_NAME="${GITHUB_REPOSITORY%%/*}"
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        
        # Get the list of files
        RELEASE_ARTIFACT=(./packages/*)
        
        export GITHUB_TOKEN=${{ secrets.DAPR_BOT_TOKEN }}
        echo "Uploading Nuget packages to GitHub Release"
        github-release upload \
          --owner $OWNER_NAME \
          --repo $REPO_NAME \
          --body "Release Dapr Pluggable Components SDK v${REL_VERSION}" \
          --tag "v${REL_VERSION}" \
          --name "Dapr .NET Pluggable Components SDK v${REL_VERSION}" \
          --prerelease true \
          ${RELEASE_ARTIFACT[*]}
    - name: Publish nuget packages to nuget.org
      if: startswith(github.ref, 'refs/tags/v') && !(endsWith(github.ref, '-rc') || endsWith(github.ref, '-dev') || endsWith(github.ref, '-prerelease'))
      run: |
        dotnet nuget push "./packages/Dapr*.nupkg" --skip-duplicate --api-key ${{ secrets.NUGETORG_DAPR_API_KEY }} --source https://api.nuget.org/v3/index.json
